/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */

description = """
    
    This is Event counter application, which might be usefull to manage count of event customers.
    Project name: ${project.name}
"""


plugins{
    application
}


repositories{
    mavenCentral()
}


dependencies{
    testImplementation("org.testng:testng:7.5")
    implementation("com.google.guava:guava:30.0-jre")
}

application{
    mainClass.set("EventCustomerCounter.App")
}


tasks.test{
    useTestNG()
}
